"""Web-verified precedent dollar anchors (Phase A enrichment, May 2026).

Patches merge onto catalog defaults in build_ri_precedents by (program_family, precedent_name).
Sources: company press releases, SEC filings, major trade press — review before investor-facing use.
"""

from __future__ import annotations

# (program_family, precedent_name) -> fields to merge (overrides catalog defaults)
VERIFIED_PATCHES: dict[tuple[str, str], dict[str, str]] = {
    # --- Tier A seeds & flagship programs ---
    ("monaghan_rna_dx", "Inflammatix (TriVerity)"): {
        "total_raised_usd_est": "200000000",
        "last_round_usd_est": "57000000",
        "value_anchor_usd": "200000000",
        "value_anchor_type": "total_raised",
        "value_source_url": "https://inflammatix.com/inflammatix-secures-57-million-to-advance-novel-diagnostic-for-patients-with-suspected-infections-or-sepsis/",
        "inferred_financing": ">$200M private + >$50M grants; $57M Series E (Sep 2024)",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("monaghan_rna_dx", "Presymptom Health (InfectiClear)"): {
        "total_raised_usd_est": "1900000",
        "last_round_usd_est": "1900000",
        "value_anchor_usd": "1900000",
        "value_anchor_type": "total_raised",
        "value_source_url": "https://www.presymptomhealth.fuel4vision.co.za/",
        "validation_status": "estimated",
        "confidence": "medium",
        "source": "web_verify_2026_05",
    },
    ("theromics_ablation", "Profound Medical (TULSA-PRO)"): {
        "total_raised_usd_est": "253000000",
        "value_anchor_usd": "253000000",
        "value_anchor_type": "market_cap",
        "value_source_url": "https://stockanalysis.com/stocks/prof/",
        "inferred_financing": "Public (NASDAQ PROF); ~$253M market cap (May 2026)",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("besio_epilepsy", "Theta Neurotech"): {
        "total_raised_usd_est": "2000000",
        "last_round_usd_est": "2000000",
        "value_anchor_usd": "2000000",
        "value_anchor_type": "last_round",
        "value_source_url": "https://www.thetaneurotech.com/",
        "validation_status": "estimated",
        "confidence": "medium",
        "source": "web_verify_2026_05",
    },
    ("brown_neurotech_implant", "Iota Biosciences (neural dust)"): {
        "total_raised_usd_est": "15000000",
        "last_round_usd_est": "127500000",
        "value_anchor_usd": "304000000",
        "value_anchor_type": "acquisition",
        "value_source_url": "https://newsroom.astellas.com/2020-10-30-Astellas-Completes-Acquisition-of-iota-Biosciences",
        "inferred_financing": (
            "$15M Series A (May 2018); $127.5M upfront acquisition (Oct 2020) "
            "+ up to $176.5M milestones; $125M five-year post-close R&D commitment"
        ),
        "inferred_development": "Preclinical → Astellas R&D partnership → acquisition → Rx+ platform",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("brown_neurotech_implant", "Synchron (Stentrode)"): {
        "total_raised_usd_est": "345000000",
        "last_round_usd_est": "200000000",
        "value_anchor_usd": "345000000",
        "value_anchor_type": "total_raised",
        "value_source_url": "https://www.businesswire.com/news/home/20251106150841/en/Synchron-Raises-200-Million-Series-D-to-Advance-Brain-Computer-Interface-Technology",
        "inferred_financing": "$345M lifetime; $200M Series D (Nov 2025)",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("brown_neurotech_implant", "Precision Neuroscience (Layer 7)"): {
        "total_raised_usd_est": "155000000",
        "last_round_usd_est": "102000000",
        "value_anchor_usd": "155000000",
        "value_anchor_type": "total_raised",
        "value_source_url": "https://www.globenewswire.com/news-release/2024/12/16/2997364/0/en/Precision-Neuroscience-Raises-102-Million-to-Advance-AI-Powered-Brain-Implant.html",
        "inferred_financing": "$155M total; $102M Series C (Dec 2024)",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("stroke_lvo_ai", "Viz.ai"): {
        "total_raised_usd_est": "289250000",
        "last_round_usd_est": "100000000",
        "value_anchor_usd": "1200000000",
        "value_anchor_type": "post_money_valuation",
        "value_source_url": "https://www.viz.ai/news/viz-ai-raises-100-million-in-series-d-funding",
        "inferred_financing": "~$289M raised; $1.2B valuation at Series D (Apr 2022)",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("stroke_lvo_ai", "RapidAI"): {
        "total_raised_usd_est": "100000000",
        "last_round_usd_est": "75000000",
        "value_anchor_usd": "100000000",
        "value_anchor_type": "total_raised",
        "value_source_url": "https://www.rapidai.com/press-release/rapid-announces-investment-led-by-vista-credit-partners",
        "inferred_financing": "~$100M total; $75M Series C (Jul 2023)",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("petzchner_digital", "Hinge Health"): {
        "total_raised_usd_est": "1487000000",
        "last_round_usd_est": "437300000",
        "value_anchor_usd": "1487000000",
        "value_anchor_type": "total_raised",
        "value_source_url": "https://sacra.com/c/hinge-health/",
        "inferred_financing": "~$1.05B pre-IPO VC + $437M IPO (May 2025)",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("petzchner_digital", "Sword Health"): {
        "total_raised_usd_est": "540000000",
        "value_anchor_usd": "4000000000",
        "value_anchor_type": "post_money_valuation",
        "value_source_url": "https://swordhealth.com/newsroom/sword-acquires-kaia-health",
        "inferred_financing": ">$500M raised; ~$4B valuation (2025); acquired Kaia for $285M (Jan 2026)",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("petzchner_digital", "Kaia Health"): {
        "value_anchor_usd": "285000000",
        "value_anchor_type": "acquisition",
        "value_source_url": "https://swordhealth.com/newsroom/sword-acquires-kaia-health",
        "inferred_financing": "Acquired by Sword Health for $285M (Jan 2026)",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("chi3l1", "GSK efimosfermin acquisition (NASH analog)"): {
        "total_raised_usd_est": "1200000000",
        "last_round_usd_est": "1200000000",
        "value_anchor_usd": "1200000000",
        "value_anchor_type": "acquisition",
        "value_source_url": "https://www.businesswire.com/news/home/20250513598541/en/GSK-to-acquire-efimosfermin-a-phase-III-ready-potential-best-in-class-specialty-medicine-to-treat-and-prevent-progression-of-steatotic-liver-disease-SLD",
        "inferred_financing": "$1.2B upfront + up to $800M milestones",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("neuro_dbs_hardware", "ClearPoint Neuro"): {
        "total_raised_usd_est": "335000000",
        "value_anchor_usd": "335000000",
        "value_anchor_type": "market_cap",
        "value_source_url": "https://finance.yahoo.com/quote/CLPT/",
        "inferred_financing": "Public (NASDAQ CLPT); ~$335M market cap (May 2026)",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("closed_loop_dbs", "NeuroPace (RNS)"): {
        "total_raised_usd_est": "540000000",
        "value_anchor_usd": "540000000",
        "value_anchor_type": "market_cap",
        "value_source_url": "https://multiples.vc/public-comps/neuropace-valuation-multiples",
        "inferred_financing": "Public (NASDAQ NPCE); ~$540M market cap; $100M revenue (FY2025)",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("brain_tumor_uptake", "Carthera (Sonocloud BBB)"): {
        "total_raised_usd_est": "55100000",
        "last_round_usd_est": "45000000",
        "value_anchor_usd": "55100000",
        "value_anchor_type": "total_raised",
        "value_source_url": "https://carthera.eu/",
        "inferred_financing": "~$55M total; Series B €42M (~$45M, Dec 2023)",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("neuro_implant_generic", "Synchron"): {
        "total_raised_usd_est": "345000000",
        "value_anchor_usd": "345000000",
        "value_anchor_type": "total_raised",
        "value_source_url": "https://www.businesswire.com/news/home/20251106150841/en/Synchron-Raises-200-Million-Series-D-to-Advance-Brain-Computer-Interface-Technology",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("neuro_implant_generic", "NeuroPace"): {
        "total_raised_usd_est": "540000000",
        "value_anchor_usd": "540000000",
        "value_anchor_type": "market_cap",
        "value_source_url": "https://investors.neuropace.com/",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("parkinson_biomarkers", "NeuroPace"): {
        "total_raised_usd_est": "540000000",
        "value_anchor_usd": "540000000",
        "value_anchor_type": "market_cap",
        "value_source_url": "https://investors.neuropace.com/",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("auranofin_catheter", "CorMedix DefenCath"): {
        "total_raised_usd_est": "570000000",
        "value_anchor_usd": "570000000",
        "value_anchor_type": "market_cap",
        "value_source_url": "https://www.macrotrends.net/stocks/charts/CRMD/cormedix-inc/market-cap",
        "inferred_financing": "Public (NASDAQ CRMD); ~$570M market cap; DefenCath commercial",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("drug_overdose_tx", "Indivior"): {
        "total_raised_usd_est": "4870000000",
        "value_anchor_usd": "4870000000",
        "value_anchor_type": "market_cap",
        "value_source_url": "https://public.com/stocks/indv/market-cap",
        "inferred_financing": "Public (NASDAQ INDV); ~$4.9B market cap; opioid-use-disorder portfolio",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("ri_pharma_chemistry", "Collegium Pharmaceutical"): {
        "total_raised_usd_est": "1180000000",
        "value_anchor_usd": "1180000000",
        "value_anchor_type": "market_cap",
        "value_source_url": "https://finance.yahoo.com/quote/COLL/",
        "inferred_financing": "Public (NASDAQ COLL); ~$1.2B market cap; pain/opioid reformulation model",
        "validation_status": "verified",
        "confidence": "high",
        "source": "web_verify_2026_05",
    },
    ("janus_delivery", "Eascra Biotech (Janus base nanoparticles)"): {
        "total_raised_usd_est": "500000",
        "last_round_usd_est": "100000",
        "value_anchor_usd": "500000",
        "value_anchor_type": "total_raised",
        "value_source_url": "https://eascrabiotech.com/",
        "inferred_financing": "SBIR/seed stage (UConn spinout); early platform",
        "validation_status": "estimated",
        "confidence": "medium",
        "source": "web_verify_2026_05",
    },
    ("monaghan_rna_dx", "Immunexpress (SeptiCyte)"): {
        "total_raised_usd_est": "50000000",
        "value_anchor_usd": "50000000",
        "value_anchor_type": "total_raised",
        "value_source_url": "https://immunexpress.com/",
        "inferred_financing": "~$50M+ venture (Biocartis partnership); host-RNA sepsis dx",
        "validation_status": "estimated",
        "confidence": "low",
        "source": "web_verify_2026_05",
    },
}
