"""Curated comparable companies/programs for RI catalog enrichment (web-sourced, user-validated over time)."""

from __future__ import annotations

# Shared precedent sets keyed by logical group; applied to case_id via CASE_PRECEDENT_GROUP.
PRECEDENT_GROUPS: dict[str, list[dict[str, str]]] = {
    "besio_epilepsy": [
        {
            "precedent_type": "startup",
            "precedent_name": "mjn-neuro (EPISERAS / mjn-SERAS)",
            "precedent_stage": "commercial_EU",
            "precedent_url": "https://mjn.cat/en/mjn-seras/",
            "precedent_notes": "Non-invasive wearable EEG; seizure-risk prediction; CE Class IIa",
            "inferred_development": "Pilot → EU commercial; digital therapeutic + device",
            "inferred_financing": "Venture-backed med device; regional commercial launch",
            "inferred_team": "Neurology/epilepsy KOLs; digital health commercial",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Device revenue + pharma distribution (Neuraxpharm)",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "Theta Neurotech",
            "precedent_stage": "pre_seed",
            "precedent_url": "https://www.thetaneurotech.com/",
            "precedent_notes": "Wearable adhesive EEG; seizure prediction",
            "inferred_development": "Pre-seed → clinical validation → Series A",
            "inferred_financing": "~$2M pre-seed (press, 2024)",
            "inferred_team": "Epilepsy clinicians + ML engineers",
            "total_raised_usd_est": "2000000",
            "last_round_usd_est": "2000000",
            "financing_strategy": "Seed VC then hospital pilot contracts",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "Precisis (EASEE)",
            "precedent_stage": "FDA_Breakthrough",
            "precedent_url": "https://www.precisis.com/",
            "precedent_notes": "Epicranial focal stimulation; multi-electrode; tripolar-adjacent",
            "inferred_development": "CE marketed → US Breakthrough → pivotal",
            "inferred_financing": "EU VC + strategic; US IDE path",
            "inferred_team": "Epilepsy surgery + neurostimulation",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Medtech venture → reimbursement",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "UNEEG Medical",
            "precedent_stage": "commercial",
            "precedent_url": "https://www.uneeg.com/",
            "precedent_notes": "Subcutaneous long-term EEG (minimally invasive monitoring)",
            "inferred_development": "510(k)/CE; hospital adoption",
            "inferred_financing": "Growth equity; EU/US subsidiaries",
            "inferred_team": "Epilepsy centers; neurology",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Medtech sales + outcomes data",
        },
    ],
    "theromics_ablation": [
        {
            "precedent_type": "ri_operating",
            "precedent_name": "Theromics Inc",
            "precedent_stage": "STTR_510k_path",
            "precedent_url": "https://www.theromicsinc.com/",
            "precedent_notes": "RI Hospital/Brown origin; HeatSYNC thermal accelerant gel",
            "inferred_development": "GLP → 510(k) adjunct to RF/MW ablation",
            "inferred_financing": "NIH STTR + seed; Slater/physician syndicate fit",
            "inferred_team": "IR + surgical oncology + Dupuy/Park",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Grant → seed → strategic device partner",
        },
        {
            "precedent_type": "public",
            "precedent_name": "Profound Medical (TULSA-PRO)",
            "precedent_stage": "commercial",
            "precedent_url": "https://profoundmedical.com/",
            "precedent_notes": "MRI-guided thermal ablation platform",
            "inferred_development": "Pivotal trials → commercial prostate ablation",
            "inferred_financing": "Public (NASDAQ PROF); capex-heavy",
            "inferred_team": "Urology/IR; med physics",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Public markets + procedure reimbursement",
        },
        {
            "precedent_type": "incumbent",
            "precedent_name": "Neuwave (Ethicon/J&J)",
            "precedent_stage": "commercial",
            "precedent_url": "https://www.ethicon.com",
            "precedent_notes": "Microwave ablation incumbent; channel for adjunct gel",
            "inferred_development": "Market access via device OEM partnership",
            "inferred_financing": "Strategic partnership vs standalone VC",
            "inferred_team": "Interventional radiology + oncology",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Licensing/co-development with ablation OEM",
        },
    ],
    "prothera_iaip": [
        {
            "precedent_type": "startup",
            "precedent_name": "Asklepion Pharmaceuticals (Kamada)",
            "precedent_stage": "commercial",
            "precedent_url": "https://www.kamada.com/",
            "precedent_notes": "IAIP / inter-alpha inhibitor pathway; sepsis and critical care biologics",
            "inferred_development": "Phase trials → hospital formulary",
            "inferred_financing": "Public biotech + partnerships",
            "inferred_team": "Critical care + neonatology",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Biologic development → licensing",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "Inflammatix (TriVerity)",
            "precedent_stage": "FDA_cleared_2025",
            "precedent_url": "https://www.inflammatix.com/",
            "precedent_notes": "Complementary sepsis host-response diagnostic (Monaghan-adjacent)",
            "inferred_development": "Dx adoption in ICU",
            "inferred_financing": "Dx VC",
            "inferred_team": "Critical care",
            "total_raised_usd_est": "100000000",
            "last_round_usd_est": "",
            "financing_strategy": "Hospital contracts",
        },
    ],
    "monaghan_rna_dx": [
        {
            "precedent_type": "startup",
            "precedent_name": "Inflammatix (TriVerity)",
            "precedent_stage": "FDA_cleared_2025",
            "precedent_url": "https://www.inflammatix.com/",
            "precedent_notes": "Host mRNA sepsis/infection; ED workflow",
            "inferred_development": "510(k) → health-system adoption",
            "inferred_financing": "$100M+ VC (Khosla, Northpond, etc.)",
            "inferred_team": "Critical care + ED + lab medicine",
            "total_raised_usd_est": "100000000",
            "last_round_usd_est": "",
            "financing_strategy": "Dx VC → hospital contracts",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "Immunexpress (SeptiCyte)",
            "precedent_stage": "FDA_cleared",
            "precedent_url": "https://immunexpress.com/products/",
            "precedent_notes": "Host RNA sepsis; PCR on Idylla",
            "inferred_development": "CLIA/LDT → ICU adoption",
            "inferred_financing": "Venture + strategic (Biocartis)",
            "inferred_team": "ICU + infectious disease",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Instrument partnership + test menu",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "Presymptom Health (InfectiClear)",
            "precedent_stage": "seed",
            "precedent_url": "https://www.presymptomhealth.fuel4vision.co.za/",
            "precedent_notes": "Host RNA infection; up to 3 days before clinical dx",
            "inferred_development": "Validation → NHS pilot → scale",
            "inferred_financing": "£1.5M seed + grants (2024)",
            "inferred_team": "Critical care PI; AMR stewardship",
            "total_raised_usd_est": "1900000",
            "last_round_usd_est": "1900000",
            "financing_strategy": "Grant + seed → health-system pilots",
        },
    ],
    "janus_delivery": [
        {
            "precedent_type": "startup",
            "precedent_name": "Eascra Biotech (Janus base nanoparticles)",
            "precedent_stage": "SBIR_seed",
            "precedent_url": "https://eascrabiotech.com/",
            "precedent_notes": "Janus nucleotide delivery; UConn spinout",
            "inferred_development": "SBIR → animal POC → Series A",
            "inferred_financing": "$100K START + SBIR Phase I",
            "inferred_team": "Drug delivery + oncology/cartilage",
            "total_raised_usd_est": "500000",
            "last_round_usd_est": "100000",
            "financing_strategy": "SBIR → seed syndicate",
        },
        {
            "precedent_type": "public",
            "precedent_name": "Ionis Pharmaceuticals",
            "precedent_stage": "public",
            "precedent_url": "https://www.ionis.com/",
            "precedent_notes": "Oligonucleotide platform",
            "inferred_development": "Platform → indication spinouts",
            "inferred_financing": "Public biotech milestones",
            "inferred_team": "Clinical pharmacology + neurology",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Pharma partnerships",
        },
        {
            "precedent_type": "public",
            "precedent_name": "Alnylam Pharmaceuticals",
            "precedent_stage": "public",
            "precedent_url": "https://www.alnylam.com/",
            "precedent_notes": "RNAi delivery platform",
            "inferred_development": "Rare disease → broader pipeline",
            "inferred_financing": "Large-cap biotech",
            "inferred_team": "Specialty pharma development",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Platform partnerships",
        },
    ],
    "phlip_imaging": [
        {
            "precedent_type": "ri_operating",
            "precedent_name": "pHLIP Inc",
            "precedent_stage": "clinical_validation",
            "precedent_url": "https://phlipinc.com/",
            "precedent_notes": "URI/Yale pHLIP spinout; Reshetnyak/Engelman fluorophore and delivery IP",
            "inferred_development": "Preclinical → IND → fluorescence-guided surgery pilot",
            "inferred_financing": "Seed + URI/Slater ecosystem; Pacific Partners/Yale investors",
            "inferred_team": "Interventional radiology + surgical oncology + pathology",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Grant → seed syndicate → strategic pharma",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "On Target Laboratories (Cytalux)",
            "precedent_stage": "FDA_approved",
            "precedent_url": "https://www.ontargetlaboratories.com/",
            "precedent_notes": "FDA-approved pafolacianine for fluorescence-guided lung cancer surgery",
            "inferred_development": "IND → pivotal → FDA approval → hospital adoption",
            "inferred_financing": "$150M+ venture (estimated)",
            "inferred_team": "Surgical oncology + IR + pathology",
            "total_raised_usd_est": "150000000",
            "last_round_usd_est": "",
            "financing_strategy": "Dx/imaging VC → hospital contracts",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "Cybrexa (alphalex)",
            "precedent_stage": "clinical",
            "precedent_url": "https://www.cybrexa.com/",
            "precedent_notes": "pHLIP-derived peptide-drug conjugates; possible Yale/URI license path",
            "inferred_development": "Clinical-stage oncology PDC → partnership",
            "inferred_financing": "Venture-backed clinical biotech",
            "inferred_team": "Surgical oncology + medical oncology",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Clinical VC → pharma partnership",
        },
        {
            "precedent_type": "incumbent",
            "precedent_name": "Indocyanine green (ICG)",
            "precedent_stage": "commercial",
            "precedent_url": "https://www.fda.gov/",
            "precedent_notes": "Incumbent NIR fluorescence imaging agent in surgery",
            "inferred_development": "Established surgical fluorescence standard",
            "inferred_financing": "Generic pharmaceutical supply",
            "inferred_team": "Surgical oncology + IR",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Incumbent comparison / differentiation",
        },
    ],
    "petzchner_digital": [
        {
            "precedent_type": "startup",
            "precedent_name": "Kaia Health",
            "precedent_stage": "acquired_2026",
            "precedent_url": "https://dtxalliance.org/products/kaia-health/",
            "precedent_notes": "Digital MSK/pain; multimodal CBT + motion coach",
            "inferred_development": "RCT → payer contracts",
            "inferred_financing": "Series C+; acquired by Sword Health",
            "inferred_team": "Pain medicine + PT + behavioral",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "B2B employer/payer",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "Hinge Health",
            "precedent_stage": "late_private",
            "precedent_url": "https://www.hingehealth.com/",
            "precedent_notes": "Virtual MSK; digital pain programs",
            "inferred_development": "Outcomes studies → enterprise sales",
            "inferred_financing": "$1B+ raised (late private)",
            "inferred_team": "PT-led care teams",
            "total_raised_usd_est": "1000000000",
            "last_round_usd_est": "",
            "financing_strategy": "Growth equity → payer ROI",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "Sword Health",
            "precedent_stage": "late_private",
            "precedent_url": "https://swordhealth.com",
            "precedent_notes": "AI MSK care; acquired Kaia 2026",
            "inferred_development": "Scale digital pain/MSK",
            "inferred_financing": "Unicorn digital health",
            "inferred_team": "Clinical ops + AI",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Enterprise B2B",
        },
    ],
    "chi3l1": [
        {
            "precedent_type": "ri_public",
            "precedent_name": "Ocean Biomedical (CHI3L1 / Elias)",
            "precedent_stage": "public_SPAC",
            "precedent_url": "https://www.globenewswire.com/news-release/2023/05/23/2674264/0/en/Ocean-Biomedical-Inc-NASDAQ-OCEA-Announces-Patent-Award-for-Novel-Cancer-Immunotherapy-Treatment-Granted-for-Prostate-Cancer-Colon-Cancer-Ovarian-Cancer-Kidney-Cancer-Breast-Cancer.html",
            "precedent_notes": "Providence RI; Brown/Elias CHI3L1 antibodies",
            "inferred_development": "Preclinical → IND-enabling → spinouts",
            "inferred_financing": "Public vehicle + university licenses",
            "inferred_team": "Med onc + translational pulmonology",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Hub-and-spoke biotech holding",
        },
        {
            "precedent_type": "research",
            "precedent_name": "Brown / RI Hospital CHI3L1 program (Elias)",
            "precedent_stage": "academic",
            "precedent_url": "https://www.sec.gov/Archives/edgar/data/1869974/000149315223010129/form10-k.htm",
            "precedent_notes": "SEC filings describe mAb and bispecific pipeline",
            "inferred_development": "Academic → Ocean license → IND",
            "inferred_financing": "NIH + philanthropy + venture spinout",
            "inferred_team": "Oncology + immunology",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "License to vehicle or newco",
        },
        {
            "precedent_type": "pharma_deal",
            "precedent_name": "GSK efimosfermin acquisition (NASH analog)",
            "precedent_stage": "phase_3_ready",
            "precedent_url": "https://www.businesswire.com/news/home/20250513598541/en/GSK-to-acquire-efimosfermin-a-phase-III-ready-potential-best-in-class-specialty-medicine-to-treat-and-prevent-progression-of-steatotic-liver-disease-SLD",
            "precedent_notes": "Fibrosis/NASH exit comp (not CHI3L1 mechanism)",
            "inferred_development": "Phase 3 → acquisition",
            "inferred_financing": "$1.2B upfront + $800M milestones",
            "inferred_team": "Hepatology development",
            "total_raised_usd_est": "1200000000",
            "last_round_usd_est": "1200000000",
            "financing_strategy": "Pharma acquisition of late-stage asset",
        },
    ],
    "brown_neurotech_implant": [
        {
            "precedent_type": "pharma_deal",
            "precedent_name": "Iota Biosciences (neural dust)",
            "precedent_stage": "acquired_2020",
            "precedent_url": "https://newsroom.astellas.com/2020-10-30-Astellas-Completes-Acquisition-of-iota-Biosciences",
            "precedent_notes": "Ultrasound-powered wireless neural dust; mm-scale battery-free implants for neural sensing/stimulation",
            "inferred_development": "Preclinical → strategic R&D → pharma acquisition",
            "inferred_financing": "$15M Series A (2018); ~$127.5M upfront acquisition (Oct 2020) + milestones",
            "inferred_team": "Neuroengineering + neurosurgery/neurology KOLs",
            "total_raised_usd_est": "15000000",
            "last_round_usd_est": "127500000",
            "financing_strategy": "Seed/Series A → corporate R&D → pharma acquisition (Astellas Rx+)",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "Synchron (Stentrode)",
            "precedent_stage": "pivotal_2026",
            "precedent_url": "https://synchron.com/",
            "precedent_notes": "Endovascular BCI; minimally invasive neural interface",
            "inferred_development": "IDE → pivotal → PMA",
            "inferred_financing": "$345M total; $200M Series D (2025)",
            "inferred_team": "Interventional neurology + neurosurgery",
            "total_raised_usd_est": "345000000",
            "last_round_usd_est": "200000000",
            "financing_strategy": "Venture → pivotal → PMA",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "Blackrock Neurotech",
            "precedent_stage": "private",
            "precedent_url": "https://www.blackrockneuro.com/",
            "precedent_notes": "Utah array; research/clinical BCI",
            "inferred_development": "Research grants → clinical trials",
            "inferred_financing": "Strategic + grants",
            "inferred_team": "Neurosurgery + BCI research",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Strategic pharma/device",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "Precision Neuroscience (Layer 7)",
            "precedent_stage": "clinical",
            "precedent_url": "https://precisionneuro.io/",
            "precedent_notes": "Thin-film cortical surface array",
            "inferred_development": "Clinical feasibility → IDE",
            "inferred_financing": "Venture (Founders Fund, etc.)",
            "inferred_team": "Neurosurgery + neurology",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "VC → strategic (Medtronic partnership)",
        },
    ],
    "wireless_biosensor_network": [
        {
            "precedent_type": "startup",
            "precedent_name": "Biowear",
            "precedent_stage": "clinical_validation",
            "precedent_url": "https://www.biowear.net/",
            "precedent_notes": "Smart textile multi-sensor networks",
            "inferred_development": "Hospital validation → deployment",
            "inferred_financing": "Venture + hospital partners",
            "inferred_team": "Cardiology + digital health",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Hospital pilot → payer",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "Senphonix (SleeveSense)",
            "precedent_stage": "early",
            "precedent_url": "https://senphonix.com/solution",
            "precedent_notes": "Wireless ward monitoring; LoRa hospital network",
            "inferred_development": "Pilot → health-system integration",
            "inferred_financing": "Seed medtech",
            "inferred_team": "Hospital medicine + IT",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Hospital SaaS + device",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "AOKNOS",
            "precedent_stage": "early",
            "precedent_url": "https://aoknos.com/",
            "precedent_notes": "AI biosensor cardiovascular risk",
            "inferred_development": "Algorithm validation → FDA path",
            "inferred_financing": "Seed",
            "inferred_team": "Cardiology",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Seed VC",
        },
    ],
    "closed_loop_dbs": [
        {
            "precedent_type": "incumbent",
            "precedent_name": "Medtronic Percept (BrainSense)",
            "precedent_stage": "FDA_adaptive_DBS",
            "precedent_url": "https://www.medtronic.com/en-us/healthcare-professionals/specialties/neurology/therapies-procedures/deep-brain-stimulation/product-portfolio/percept-family.html",
            "precedent_notes": "Closed-loop/adaptive DBS; sensing leads",
            "inferred_development": "Post-market adaptive DBS rollout",
            "inferred_financing": "Strategic incumbent (not VC seed)",
            "inferred_team": "Movement disorders neurology + neurosurgery",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Out-license or RI spinout vs compete",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "NeuroPace (RNS)",
            "precedent_stage": "public",
            "precedent_url": "https://www.neuropace.com/",
            "precedent_notes": "Responsive neurostimulation; closed-loop epilepsy",
            "inferred_development": "PMA → post-approval studies",
            "inferred_financing": "Public (NPCE)",
            "inferred_team": "Epilepsy + neurosurgery",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Public medtech",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "Newronika (AlphaDBS)",
            "precedent_stage": "investigational_US",
            "precedent_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC11524207/",
            "precedent_notes": "Adaptive closed-loop DBS (EU)",
            "inferred_development": "Clinical trials → CE/FDA",
            "inferred_financing": "EU venture",
            "inferred_team": "Movement disorders",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Venture → strategic",
        },
    ],
    "stroke_lvo_ai": [
        {
            "precedent_type": "startup",
            "precedent_name": "Viz.ai",
            "precedent_stage": "growth",
            "precedent_url": "https://www.viz.ai/",
            "precedent_notes": "LVO triage + care coordination",
            "inferred_development": "Health-system SaaS scale",
            "inferred_financing": "$200M+ raised",
            "inferred_team": "Stroke neurology + radiology",
            "total_raised_usd_est": "200000000",
            "last_round_usd_est": "",
            "financing_strategy": "Enterprise stroke networks",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "RapidAI",
            "precedent_stage": "growth",
            "precedent_url": "https://www.rapidai.com/",
            "precedent_notes": "LVO + perfusion AI",
            "inferred_development": "FDA cleared → hospital contracts",
            "inferred_financing": "Growth equity",
            "inferred_team": "Neuro IR + neurology",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Per-study or SaaS pricing",
        },
    ],
    "parkinson_biomarkers": [
        {
            "precedent_type": "incumbent",
            "precedent_name": "Medtronic Percept sensing",
            "precedent_stage": "commercial",
            "precedent_url": "https://www.medtronic.com/en-us/healthcare-professionals/specialties/neurology/therapies-procedures/deep-brain-stimulation/product-portfolio/percept-family.html",
            "precedent_notes": "Neural biomarkers for programming",
            "inferred_development": "Regulatory clearance for biomarker-guided therapy",
            "inferred_financing": "Strategic",
            "inferred_team": "Movement disorders",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Partner with incumbent",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "Rune Labs (StriveStudy)",
            "precedent_stage": "commercial",
            "precedent_url": "https://www.runelabs.io/",
            "precedent_notes": "PD digital biomarkers + Apple Watch",
            "inferred_development": "FDA digital biomarker path",
            "inferred_financing": "Venture",
            "inferred_team": "Neurology + digital health",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Pharma/device partnerships",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "NeuroPace",
            "precedent_stage": "public",
            "precedent_url": "https://www.neuropace.com/",
            "precedent_notes": "Chronic neural recording biomarkers",
            "inferred_development": "Long-term IDE/PMA evidence",
            "inferred_financing": "Public",
            "inferred_team": "Epilepsy/neurology",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Public medtech",
        },
    ],
    "neuro_implant_generic": [
        {
            "precedent_type": "startup",
            "precedent_name": "NeuroPace",
            "precedent_stage": "public",
            "precedent_url": "https://www.neuropace.com/",
            "precedent_notes": "Brain implantable sensing/stimulation",
            "inferred_development": "PMA + post-market",
            "inferred_financing": "Public",
            "inferred_team": "Neurosurgery + neurology",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Venture → IPO",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "Synchron",
            "precedent_stage": "pivotal",
            "precedent_url": "https://synchron.com/",
            "precedent_notes": "Implantable neural interface",
            "inferred_development": "Pivotal trial",
            "inferred_financing": "$345M total funding",
            "inferred_team": "Interventional neurology",
            "total_raised_usd_est": "345000000",
            "last_round_usd_est": "",
            "financing_strategy": "Late-stage VC",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "Blackrock Neurotech",
            "precedent_stage": "private",
            "precedent_url": "https://www.blackrockneuro.com/",
            "precedent_notes": "Research-grade implants",
            "inferred_development": "Clinical translation",
            "inferred_financing": "Strategic",
            "inferred_team": "Neurosurgery research",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Grants + strategic",
        },
    ],
    "neuro_dbs_hardware": [
        {
            "precedent_type": "incumbent",
            "precedent_name": "Boston Scientific Vercise",
            "precedent_stage": "commercial",
            "precedent_url": "https://www.bostonscientific.com/",
            "precedent_notes": "DBS leads and IPGs",
            "inferred_development": "Commercial neurostimulation",
            "inferred_financing": "Strategic",
            "inferred_team": "Neurosurgery",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "OEM partnership",
        },
        {
            "precedent_type": "incumbent",
            "precedent_name": "Medtronic SenSight leads",
            "precedent_stage": "commercial",
            "precedent_url": "https://www.medtronic.com/",
            "precedent_notes": "Directional DBS leads",
            "inferred_development": "510(k) device line extensions",
            "inferred_financing": "Strategic",
            "inferred_team": "Neurosurgery + neurology",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "License to big medtech",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "ClearPoint Neuro",
            "precedent_stage": "public",
            "precedent_url": "https://www.clearpointneuro.com/",
            "precedent_notes": "MRI-guided intervention platform",
            "inferred_development": "Commercial neuro navigation",
            "inferred_financing": "Public small-cap",
            "inferred_team": "Neurosurgery",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Public medtech",
        },
    ],
    "brain_imaging": [
        {
            "precedent_type": "startup",
            "precedent_name": "Hyperfine (Swoop MRI)",
            "precedent_stage": "commercial",
            "precedent_url": "https://hyperfine.io/",
            "precedent_notes": "Portable MRI; high-resolution brain imaging angle",
            "inferred_development": "510(k) → hospital adoption",
            "inferred_financing": "SPAC/public",
            "inferred_team": "Radiology + neurology",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Device + SaaS",
        },
        {
            "precedent_type": "research",
            "precedent_name": "Academic high-resolution neuroimaging (Brown)",
            "precedent_stage": "academic",
            "precedent_url": "",
            "precedent_notes": "University lab → spinout or license",
            "inferred_development": "NIH grants → seed",
            "inferred_financing": "SBIR + university translational funds",
            "inferred_team": "Neuroscience + radiology",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Grant → spinout",
        },
    ],
    "ortho_mri_ai": [
        {
            "precedent_type": "startup",
            "precedent_name": "OrthoPred (DeepKnee)",
            "precedent_stage": "clinical_validation",
            "precedent_url": "https://orthopred.com/",
            "precedent_notes": "Autonomous knee MRI interpretation",
            "inferred_development": "CE/FDA software as medical device",
            "inferred_financing": "Seed/Series A imaging AI",
            "inferred_team": "Orthopedics + radiology",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "SaMD + PACS integration",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "AIKESO",
            "precedent_stage": "early",
            "precedent_url": "https://aikeso.com/",
            "precedent_notes": "3D joint reconstruction; surgical planning",
            "inferred_development": "Clinical pilots → FDA",
            "inferred_financing": "Seed (Switzerland)",
            "inferred_team": "Orthopedic surgery",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "EU seed → US expansion",
        },
        {
            "precedent_type": "research",
            "precedent_name": "LigaNET (ACL reinjury prediction)",
            "precedent_stage": "research",
            "precedent_url": "https://www.medrxiv.org/content/10.1101/2023.07.25.23293102v1",
            "precedent_notes": "Multi-modal MRI reinjury model",
            "inferred_development": "Academic validation → spinout",
            "inferred_financing": "NIH → seed",
            "inferred_team": "Orthopedics + radiology",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "License to SaMD company",
        },
    ],
    "auranofin_catheter": [
        {
            "precedent_type": "research",
            "precedent_name": "Brown/RI Hospital auranofin catheter (published)",
            "precedent_stage": "precommercial",
            "precedent_url": "https://engineering.brown.edu/news/2019-03-07/germ-fighting-catheter-coating-may-help-prevent-infections",
            "precedent_notes": "Same invention family; publication + patent",
            "inferred_development": "GLP → 510(k) catheter coating",
            "inferred_financing": "University translational + Slater",
            "inferred_team": "ID + critical care + device",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Spinout + strategic catheter OEM",
        },
        {
            "precedent_type": "incumbent",
            "precedent_name": "CorMedix DefenCath",
            "precedent_stage": "FDA_approved",
            "precedent_url": "https://www.cormedix.com/",
            "precedent_notes": "Antimicrobial catheter lock; infection prevention",
            "inferred_development": "Commercial infection prevention",
            "inferred_financing": "Public medtech",
            "inferred_team": "Nephrology/ICU",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Regulatory + hospital GPO",
        },
        {
            "precedent_type": "research",
            "precedent_name": "Frontiers publication (auranofin PU coating)",
            "precedent_stage": "published",
            "precedent_url": "https://www.frontiersin.org/journals/cellular-and-infection-microbiology/articles/10.3389/fcimb.2019.00037/full",
            "precedent_notes": "Scientific precedent for coating claims",
            "inferred_development": "Evidence package for 510(k)",
            "inferred_financing": "Grant-funded science",
            "inferred_team": "Academic ID + materials",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "SBIR + device spinout",
        },
    ],
    "rna_virus_dx": [
        {
            "precedent_type": "startup",
            "precedent_name": "Cue Health",
            "precedent_stage": "public_troubled",
            "precedent_url": "https://www.cuehealth.com/",
            "precedent_notes": "Molecular POC diagnostics",
            "inferred_development": "FDA EUA/510(k) path",
            "inferred_financing": "Public; post-COVID restructuring",
            "inferred_team": "ID + lab medicine",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Dx venture",
        },
        {
            "precedent_type": "incumbent",
            "precedent_name": "Abbott ID NOW",
            "precedent_stage": "commercial",
            "precedent_url": "https://www.abbott.com/",
            "precedent_notes": "POC molecular channel benchmark",
            "inferred_development": "Commercial scale",
            "inferred_financing": "Strategic",
            "inferred_team": "Lab + ID",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Partner vs compete",
        },
    ],
    "speech_assistive": [
        {
            "precedent_type": "startup",
            "precedent_name": "Pison",
            "precedent_stage": "growth",
            "precedent_url": "https://pison.com/",
            "precedent_notes": "Neural sensing + assistive communication",
            "inferred_development": "Consumer/wearable → clinical",
            "inferred_financing": "Venture",
            "inferred_team": "Neurology + assistive tech",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "VC + strategic",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "Neuralink (speech/BCI)",
            "precedent_stage": "clinical_trial",
            "precedent_url": "https://neuralink.com/",
            "precedent_notes": "High-bandwidth BCI including speech goals",
            "inferred_development": "IDE clinical trials",
            "inferred_financing": "$1B+ private",
            "inferred_team": "Neurosurgery",
            "total_raised_usd_est": "1000000000",
            "last_round_usd_est": "",
            "financing_strategy": "Late-stage private",
        },
    ],
    "absorbable_polymer": [
        {
            "precedent_type": "startup",
            "precedent_name": "Tepha (resorbable polymers)",
            "precedent_stage": "commercial",
            "precedent_url": "https://www.tephainc.com/",
            "precedent_notes": "Absorbable biomaterials for devices",
            "inferred_development": "510(k) device components",
            "inferred_financing": "Growth/medtech",
            "inferred_team": "Orthopedics + plastics surgery",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "B2B materials + devices",
        },
        {
            "precedent_type": "incumbent",
            "precedent_name": "Evonik RESOMER",
            "precedent_stage": "commercial",
            "precedent_url": "https://medical.evonik.com/",
            "precedent_notes": "Absorbable polymer supply",
            "inferred_development": "Supplier partnership",
            "inferred_financing": "Strategic",
            "inferred_team": "Device engineering",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "License materials",
        },
    ],
    "drug_overdose_tx": [
        {
            "precedent_type": "public",
            "precedent_name": "Indivior",
            "precedent_stage": "commercial",
            "precedent_url": "https://www.indivior.com/",
            "precedent_notes": "Opioid use disorder therapeutics",
            "inferred_development": "NDA/BLA path",
            "inferred_financing": "Public pharma",
            "inferred_team": "Addiction medicine + EM",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Pharma development",
        },
        {
            "precedent_type": "startup",
            "precedent_name": "Harm Reduction Therapeutics",
            "precedent_stage": "nonprofit_commercial",
            "precedent_url": "https://www.harmreductiontherapeutics.org/",
            "precedent_notes": "OTC naloxone model",
            "inferred_development": "Regulatory → distribution",
            "inferred_financing": "Grants + philanthropy",
            "inferred_team": "Public health",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Non-dilutive + partnerships",
        },
    ],
    "brain_tumor_uptake": [
        {
            "precedent_type": "startup",
            "precedent_name": "Carthera (Sonocloud BBB)",
            "precedent_stage": "clinical",
            "precedent_url": "https://www.carthera.eu/",
            "precedent_notes": "BBB opening for brain drug delivery",
            "inferred_development": "Clinical trials in neuro-onc",
            "inferred_financing": "EU venture",
            "inferred_team": "Neuro-oncology",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Venture → pharma",
        },
    ],
    "marine_natural_products": [
        {
            "precedent_type": "research",
            "precedent_name": "URI marine natural product program",
            "precedent_stage": "academic",
            "precedent_url": "https://web.uri.edu/pharmacy/",
            "precedent_notes": "University marine biodiscovery",
            "inferred_development": "Grant → lead optimization → spinout",
            "inferred_financing": "NIH + URI translational",
            "inferred_team": "Microbiology + medicinal chemistry",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Grant → seed biotech",
        },
    ],
    "ri_pharma_chemistry": [
        {
            "precedent_type": "ri_operating",
            "precedent_name": "Rhodes Technologies",
            "precedent_stage": "operating",
            "precedent_url": "https://www.rhodestech.com/",
            "precedent_notes": "RI-based API/opioid manufacturing",
            "inferred_development": "Process validation → commercial supply",
            "inferred_financing": "Operating cash flow + SSBCI/capex",
            "inferred_team": "CMC + regulatory affairs",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Slater SSBCI + bank; not classic VC",
        },
        {
            "precedent_type": "ri_operating",
            "precedent_name": "Noramco",
            "precedent_stage": "operating",
            "precedent_url": "https://www.noramco.com/",
            "precedent_notes": "Controlled-substance synthesis RI",
            "inferred_development": "CMC scale-up",
            "inferred_financing": "Private operating company",
            "inferred_team": "Process chemistry + QA",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Capex expansion financing",
        },
        {
            "precedent_type": "public",
            "precedent_name": "Collegium Pharmaceutical",
            "precedent_stage": "public",
            "precedent_url": "https://www.collegiumpharma.com/",
            "precedent_notes": "Opioid reformulation commercial model",
            "inferred_development": "FDA approvals → commercialization",
            "inferred_financing": "Public pharma",
            "inferred_team": "Pain medicine commercial",
            "total_raised_usd_est": "",
            "last_round_usd_est": "",
            "financing_strategy": "Public markets",
        },
    ],
    "general_ri_spinout": [
        {
            "precedent_type": "program",
            "precedent_name": "NIH SBIR Phase I/II",
            "precedent_stage": "grant",
            "precedent_url": "https://www.sbir.gov/",
            "precedent_notes": "Typical first external capital for RI university spinouts",
            "inferred_development": "Phase I → Phase II → seed",
            "inferred_financing": "$250K–$2M non-dilutive",
            "inferred_team": "PI + university TTO",
            "total_raised_usd_est": "1500000",
            "last_round_usd_est": "",
            "financing_strategy": "SBIR then physician syndicate + Slater match",
        },
        {
            "precedent_type": "program",
            "precedent_name": "Brown/RI Hospital translational funds",
            "precedent_stage": "grant",
            "precedent_url": "",
            "precedent_notes": "Bridge before syndicate",
            "inferred_development": "Pilot grants → spinout",
            "inferred_financing": "$50K–$500K",
            "inferred_team": "Academic PI + clinicians",
            "total_raised_usd_est": "250000",
            "last_round_usd_est": "",
            "financing_strategy": "Philanthropy + hospital innovation",
        },
    ],
}

# Map each active catalog case_id to a precedent group key.
CASE_PRECEDENT_GROUP: dict[str, str] = {
    "auto_rhode_island_biomedical_detecting_electrical_electrode_locali": "besio_epilepsy",
    "auto_rhode_island_biomedical_electrode": "besio_epilepsy",
    "auto_rhode_island_biomedical_contact_prepared_sensors_surfaces_usa": "besio_epilepsy",
    "theromics_ri": "theromics_ablation",
    "monaghan_sepsis_diagnostic_ri": "monaghan_rna_dx",
    "auto_rhode_island_antibodies_covid_deep_predicting_sequencing_surv": "monaghan_rna_dx",
    "nanode_ri": "janus_delivery",
    "phlip_therapeutics_ri": "phlip_imaging",
    "cbt_pain_digital_platform_ri": "petzchner_digital",
    "auto_brown_university_anti_antibody_bispecific_chi3l1_reagents_relatin": "chi3l1",
    "auto_brown_university_implantable_neural_wireless": "brown_neurotech_implant",
    "auto_brown_university_biomedical_biosensor_diagnostics_large_networks": "wireless_biosensor_network",
    "auto_rhode_island_behavioral_biomarkers_brain_closed_deep_features": "closed_loop_dbs",
    "auto_rhode_island_detection_large_occlusion_prediction_vessel": "stroke_lvo_ai",
    "auto_brown_university_biomarkers_disease_neural_parkinson": "parkinson_biomarkers",
    "auto_brown_university_interrogation_neural_platform": "neuro_implant_generic",
    "auto_brown_university_brain_high_imaging_resolution_spatiotemporal": "brain_imaging",
    "auto_rhode_island_alloy_array_brain_cord_electrode_invasive_memory": "neuro_dbs_hardware",
    "auto_brown_university_annulus_biocompatible_brain_catheter_coupled_ele": "neuro_dbs_hardware",
    "auto_rhode_island_brain_implantable": "neuro_implant_generic",
    "auto_rhode_island_fixation_intracranial": "neuro_dbs_hardware",
    "auto_brown_university_biopsy_burr_hole_mounted_stereotactic": "neuro_dbs_hardware",
    "auto_brown_university_assay_diagnostic_virus": "rna_virus_dx",
    "auto_rhode_island_anterior_cruciate_invasive_ligament_measurement": "ortho_mri_ai",
    "auto_rhode_island_connective_evaluate_pipeline_reinjury_risk_tissu": "ortho_mri_ai",
    "auto_rhode_island_antibacterial_antibiofilm_auranofin_catheter_coa": "auranofin_catheter",
    "auto_united_states_communication_facilitating_individuals_speak_spe": "speech_assistive",
    "auto_university_rhode_biomedical_brassylate_copolymers_dioxanone_ethyl": "absorbable_polymer",
    "auto_brown_university_drug_overdose": "drug_overdose_tx",
    "auto_brown_university_brain_chemotherapeutic_drug_enhancing_tumors_upt": "brain_tumor_uptake",
    "auto_regents_university_anti_compounds_inflammatory_inhibition_making_qu": "marine_natural_products",
    "prothera_iaip_ri": "prothera_iaip",
    "auto_rhode_island_activity_brain_detecting_pain_using": "saab_pain_neuro",
    "auto_rhode_island_biomarker_brugada_circulating_syndrome": "brugada_dx",
    "auto_rhode_island_conductivity_dose_fields_hydrogel_impacts_skin_t": "ttf_neuro_onc",
    "auto_neurotech_analyte_apparatuses_diffusive_implantable_packag": "neurotech_ect",
    "auto_neurotech_cell_disorders_encapsulated_ophthalmic_therapy": "neurotech_ect",
    "auto_univ_brown_chiplet_intranet_large_recordiing_scale_stimulat": "brown_neurotech_implant",
    "auto_rhode_island_brain_enhancer_primary_rnas_targeting_tumors": "brain_tumor_rna",
    "auto_bryant_university_antibacterial_compounds_making_same_using": "brown_antibacterial",
}

# All ri_pharma_chemistry case_ids share one group.
PHARMA_PREFIXES = (
    "auto_rhodes_technologies_",
    "auto_noramco_",
    "auto_purdue_",
)
